/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class BarangKeluarPage extends javax.swing.JFrame {

    private Connection conn = DatabaseConnection.connect();
    /**
     * Creates new form BarangKeluarPage
     */
    public BarangKeluarPage() {
        initComponents();
        tampilData();
        
         btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahData();
            }
        });
         
          btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahData();
            }
        });
          
           tabelBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMasukMouseClicked(evt);
            }
        });
           
           btnUlangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangData();  
            }
        });
           
           btnHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusData();  
            }
        });
           
           txtCari.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                cariBarang();  
            }
        });
           
           btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakLaporan(); 
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNamaBarangKeluar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtJumlahBarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dateBarangKeluar = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaKeterangan = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnUlangInput = new javax.swing.JButton();
        btnHapusData = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelBarangKeluar = new javax.swing.JTable();
        btnKembaliMenuUtama = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 255, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("BARANG KELUAR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(34, 34, 34))
        );

        jLabel12.setText("Nama Barang");

        jLabel13.setText("Jumlah");

        jLabel14.setText("Keterangan");

        jLabel15.setText("Tanggal Keluar");

        txtAreaKeterangan.setColumns(20);
        txtAreaKeterangan.setRows(5);
        jScrollPane5.setViewportView(txtAreaKeterangan);

        btnSubmit.setText("Tambah");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");

        btnUlangInput.setText("Ulang");

        btnHapusData.setText("Hapus");

        tabelBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Jumlah", "Tanggal Keluar", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabelBarangKeluar);

        btnKembaliMenuUtama.setText("Kembali");
        btnKembaliMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliMenuUtamaActionPerformed(evt);
            }
        });

        jLabel16.setText("Cari barang berdasarkan nama");

        btnCetak.setText("Cetak Laporan Barang Keluar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnKembaliMenuUtama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUlangInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)
                                                .addComponent(btnCetak))))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNamaBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dateBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(22, 22, 22))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(20, 20, 20)
                        .addComponent(btnUlangInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusData))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKembaliMenuUtama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtNamaBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnKembaliMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliMenuUtamaActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliMenuUtamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangKeluarPage().setVisible(true);
            }
        });
    }
    
    private void tambahData() {
    String namaBarang = txtNamaBarangKeluar.getText();
    int jumlah = Integer.parseInt(txtJumlahBarang.getText());
    
    
    if (dateBarangKeluar.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Tanggal tidak boleh kosong!");
        return;
    }

    
    Date tanggalKeluar = new Date(dateBarangKeluar.getDate().getTime());
    String keterangan = txtAreaKeterangan.getText();
    
    String sql = "INSERT INTO barang_keluar (nama_barang, jumlah, tanggal_keluar, keterangan) VALUES (?, ?, ?, ?)";
    
    try {
       
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, namaBarang);
        pst.setInt(2, jumlah);
        pst.setDate(3, tanggalKeluar); 
        pst.setString(4, keterangan);
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        tampilData();  
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}
    
    private void tampilData() {
        String sql = "SELECT * FROM barang_keluar";
        
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            
            
            tabelBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {"ID Barang", "Nama Barang", "Jumlah", "Tanggal Keluar", "Keterangan"}
            ));
            
           
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_keluar"),
                    rs.getString("nama_barang"),
                    rs.getInt("jumlah"),
                    rs.getDate("tanggal_keluar"),
                    rs.getString("keterangan")
                };
                ((javax.swing.table.DefaultTableModel) tabelBarangKeluar.getModel()).addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }
    
    private void ubahData() {
        int selectedRow = tabelBarangKeluar.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah!");
            return;
        }

        
        int idBarang = (int) tabelBarangKeluar.getValueAt(selectedRow, 0);
        String namaBarang = txtNamaBarangKeluar.getText();
        int jumlah = Integer.parseInt(txtJumlahBarang.getText());

        if (dateBarangKeluar.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal tidak boleh kosong!");
            return;
        }

        Date tanggalKeluar = new Date(dateBarangKeluar.getDate().getTime());
        String keterangan = txtAreaKeterangan.getText();

        String sql = "UPDATE barang_keluar SET nama_barang = ?, jumlah = ?, tanggal_keluar = ?, keterangan = ? WHERE id_keluar = ?";
        
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaBarang);
            pst.setInt(2, jumlah);
            pst.setDate(3, tanggalKeluar);
            pst.setString(4, keterangan);
            pst.setInt(5, idBarang);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
            tampilData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }
    
    private void ulangData() {
        txtNamaBarangKeluar.setText("");
        txtJumlahBarang.setText("");
        txtAreaKeterangan.setText("");
        dateBarangKeluar.setDate(null); 
    }
    
    private void hapusData() {
        int selectedRow = tabelBarangKeluar.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus!");
            return;
        }

        
        int idBarang = (int) tabelBarangKeluar.getValueAt(selectedRow, 0);

        
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM barang_keluar WHERE id_keluar = ?";
            
            try {
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, idBarang);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                tampilData();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            }
        }
    }
    
    private void cariBarang() {
    String keyword = txtCari.getText().toLowerCase(); 
    DefaultTableModel model = (DefaultTableModel) tabelBarangKeluar.getModel();  
    int rowCount = model.getRowCount(); 

    
    for (int i = 0; i < rowCount; i++) {
        String namaBarang = model.getValueAt(i, 1).toString().toLowerCase(); 

        if (namaBarang.contains(keyword)) {
            tabelBarangKeluar.setRowSelectionAllowed(true); 
            tabelBarangKeluar.addRowSelectionInterval(i, i); 
        } else {
            
            tabelBarangKeluar.removeRowSelectionInterval(i, i);
        }
    }
}
    
    private void cetakLaporan() {
        try {
            FileWriter writer = new FileWriter("laporan_barang_keluar.txt");  

            
            writer.write("Laporan Barang Keluar\n");
            writer.write("====================\n");
            writer.write(String.format("%-10s %-20s %-10s %-15s %-20s\n", "ID Barang", "Nama Barang", "Jumlah", "Tanggal Keluar", "Keterangan"));

            
            DefaultTableModel model = (DefaultTableModel) tabelBarangKeluar.getModel();
            int rowCount = model.getRowCount();

            for (int i = 0; i < rowCount; i++) {
                String idBarang = model.getValueAt(i, 0).toString();
                String namaBarang = model.getValueAt(i, 1).toString();
                String jumlah = model.getValueAt(i, 2).toString();
                String tanggalKeluar = model.getValueAt(i, 3).toString();
                String keterangan = model.getValueAt(i, 4).toString();

                writer.write(String.format("%-10s %-20s %-10s %-15s %-20s\n", idBarang, namaBarang, jumlah, tanggalKeluar, keterangan));
            }

            writer.close();  
            JOptionPane.showMessageDialog(null, "Laporan berhasil dicetak ke laporan_barang_keluar.txt");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencetak laporan: " + e.getMessage());
        }
    }
    
    private void tabelBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tabelBarangKeluar.getSelectedRow();
        
        if (selectedRow != -1) {
            txtNamaBarangKeluar.setText(tabelBarangKeluar.getValueAt(selectedRow, 1).toString());
            txtJumlahBarang.setText(tabelBarangKeluar.getValueAt(selectedRow, 2).toString());
            dateBarangKeluar.setDate((Date) tabelBarangKeluar.getValueAt(selectedRow, 3));
            txtAreaKeterangan.setText(tabelBarangKeluar.getValueAt(selectedRow, 4).toString());
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapusData;
    private javax.swing.JButton btnKembaliMenuUtama;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUlangInput;
    private com.toedter.calendar.JDateChooser dateBarangKeluar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tabelBarangKeluar;
    private javax.swing.JTextArea txtAreaKeterangan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtNamaBarangKeluar;
    // End of variables declaration//GEN-END:variables
}
