/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class TransaksiPage extends javax.swing.JFrame {
    
    private Connection conn = DatabaseConnection.connect();

    /**
     * Creates new form TransaksiPage
     */
    public TransaksiPage() {
        initComponents();
        tampilData();
        
    btnSubmit.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        tambahData();
    }
    });
    
    btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahData();
            }
        });
    
    btnHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusData();  
            }
        });
    
    btnUlangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetForm();  
            }
        });
    
    btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakLaporan();  
            }
        });
        
    txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyReleased(java.awt.event.KeyEvent evt) {
        hitungTotalHarga();
    }
    });

    txtHargaSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyReleased(java.awt.event.KeyEvent evt) {
        hitungTotalHarga();
    }
    });
    
    tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
    
    


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        cbbTipeTransaksi = new javax.swing.JComboBox<>();
        txtHargaSatuan = new javax.swing.JTextField();
        txtHargaTotal = new javax.swing.JTextField();
        dateTransaksi = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaKeterangan = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnUlangInput = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnHapusData = new javax.swing.JButton();
        btnKembaliMenuUtama = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 255, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("TRANSAKSI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel1.setText("Nama Barang");

        jLabel2.setText("Jumlah");

        jLabel3.setText("Harga Satuan (Rp)");

        jLabel4.setText("Tipe Transaksi");

        jLabel5.setText("Harga Total (Rp)");

        jLabel6.setText("Tanggal Transaksi");

        jLabel7.setText("Keterangan");

        cbbTipeTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masuk", "keluar" }));

        txtHargaTotal.setEditable(false);
        txtHargaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaTotalActionPerformed(evt);
            }
        });

        txtAreaKeterangan.setColumns(20);
        txtAreaKeterangan.setRows(5);
        jScrollPane1.setViewportView(txtAreaKeterangan);

        btnSubmit.setText("Tambah");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");

        btnUlangInput.setText("Ulang");

        btnCetak.setText("Cetak Laporan Transaksi");

        btnHapusData.setText("Hapus");

        btnKembaliMenuUtama.setText("Kembali");
        btnKembaliMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliMenuUtamaActionPerformed(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama Barang", "Jumlah", "Tipe Transaksi", "Harga Satuan (Rp)", "Harga Total (Rp)", "Tanggal Transaksi", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelTransaksi);
        if (tabelTransaksi.getColumnModel().getColumnCount() > 0) {
            tabelTransaksi.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtHargaTotal)
                                .addComponent(cbbTipeTransaksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHargaSatuan, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dateTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCetak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKembaliMenuUtama)))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUlangInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnHapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbbTipeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtHargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSubmit)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah)
                                .addGap(20, 20, 20)
                                .addComponent(btnUlangInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusData)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dateTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCetak)
                            .addComponent(btnKembaliMenuUtama)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaTotalActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnKembaliMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliMenuUtamaActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliMenuUtamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPage().setVisible(true);
            }
        });
    }
   
    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {
    int selectedRow = tabelTransaksi.getSelectedRow(); 
    if (selectedRow == -1) {
        return;
    }

    
    txtNamaBarang.setText(tabelTransaksi.getValueAt(selectedRow, 1).toString());
    txtJumlah.setText(tabelTransaksi.getValueAt(selectedRow, 2).toString());
    cbbTipeTransaksi.setSelectedItem(tabelTransaksi.getValueAt(selectedRow, 3).toString());
    txtHargaSatuan.setText(tabelTransaksi.getValueAt(selectedRow, 4).toString());
    txtHargaTotal.setText(tabelTransaksi.getValueAt(selectedRow, 5).toString());

    
    java.util.Date tanggal = (java.util.Date) tabelTransaksi.getValueAt(selectedRow, 6);
    dateTransaksi.setDate(tanggal);

    txtAreaKeterangan.setText(tabelTransaksi.getValueAt(selectedRow, 7).toString());
}

    
    private void tambahData() {
    String namaBarang = txtNamaBarang.getText();
    int jumlah;
    double hargaSatuan;
    String tipeTransaksi = cbbTipeTransaksi.getSelectedItem().toString();
    String keterangan = txtAreaKeterangan.getText();

    try {
        jumlah = Integer.parseInt(txtJumlah.getText());
        hargaSatuan = Double.parseDouble(txtHargaSatuan.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Jumlah dan Harga Satuan harus berupa angka!");
        return;
    }

    if (dateTransaksi.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Tanggal tidak boleh kosong!");
        return;
    }

    double hargaTotal = jumlah * hargaSatuan;
    java.sql.Date tanggalTransaksi = new java.sql.Date(dateTransaksi.getDate().getTime());

    String sql = "INSERT INTO transaksi (nama_barang, jumlah, tipe_transaksi, harga_satuan, harga_total, tanggal_transaksi, keterangan) VALUES (?, ?, ?, ?, ?, ?, ?)";

    try {
        PreparedStatement pst = DatabaseConnection.connect().prepareStatement(sql);
        pst.setString(1, namaBarang);
        pst.setInt(2, jumlah);
        pst.setString(3, tipeTransaksi);
        pst.setDouble(4, hargaSatuan);
        pst.setDouble(5, hargaTotal);
        pst.setDate(6, tanggalTransaksi);
        pst.setString(7, keterangan);

        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        tampilData();
        resetForm();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}
    
    
    private void ubahData() {
    
    int selectedRow = tabelTransaksi.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah!");
        return;
    }

    
    int id_transaksi = (int) tabelTransaksi.getValueAt(selectedRow, 0); 
    String namaBarang = txtNamaBarang.getText();
    String tipeTransaksi = cbbTipeTransaksi.getSelectedItem().toString();
    int jumlah;
    double hargaSatuan;
    String keterangan = txtAreaKeterangan.getText();

    
    try {
        jumlah = Integer.parseInt(txtJumlah.getText());
        hargaSatuan = Double.parseDouble(txtHargaSatuan.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Jumlah dan Harga Satuan harus berupa angka!");
        return;
    }

    
    if (dateTransaksi.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Tanggal tidak boleh kosong!");
        return;
    }

    double hargaTotal = jumlah * hargaSatuan;
    java.sql.Date tanggalTransaksi = new java.sql.Date(dateTransaksi.getDate().getTime());

    
    String sql = "UPDATE transaksi SET nama_barang = ?, jumlah = ?, tipe_transaksi = ?, harga_satuan = ?, harga_total = ?, tanggal_transaksi = ?, keterangan = ? WHERE id_transaksi = ?";

    try {
        PreparedStatement pst = DatabaseConnection.connect().prepareStatement(sql);
        pst.setString(1, namaBarang);
        pst.setInt(2, jumlah);
        pst.setString(3, tipeTransaksi);
        pst.setDouble(4, hargaSatuan);
        pst.setDouble(5, hargaTotal);
        pst.setDate(6, tanggalTransaksi);
        pst.setString(7, keterangan);
        pst.setInt(8, id_transaksi);

        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil diubah!");

        
        tampilData();
        resetForm();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}
    
    private void hapusData() {
        int selectedRow = tabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus!");
            return;
        }

        
        int idTransaksi = (int) tabelTransaksi.getValueAt(selectedRow, 0);

        
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM transaksi WHERE id_transaksi = ?";
            
            try {
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, idTransaksi);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                tampilData();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            }
        }
    }


    
    private void tampilData() {
    String sql = "SELECT * FROM transaksi";

    try {
        PreparedStatement pst = DatabaseConnection.connect().prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"ID Transaksi", "Nama Barang", "Jumlah", "Tipe Transaksi", "Harga Satuan", "Harga Total", "Tanggal Transaksi", "Keterangan"}
        ));

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id_transaksi"),
                rs.getString("nama_barang"),
                rs.getInt("jumlah"),
                rs.getString("tipe_transaksi"),
                rs.getDouble("harga_satuan"),
                rs.getDouble("harga_total"),
                rs.getDate("tanggal_transaksi"),
                rs.getString("keterangan")
            };
            ((javax.swing.table.DefaultTableModel) tabelTransaksi.getModel()).addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}
    
    private void cetakLaporan() {
    try {
        
        FileWriter writer = new FileWriter("laporan_transaksi.txt");

        
        writer.write("Laporan Transaksi Keuangan\n");
        writer.write("==========================\n");
        writer.write(String.format("%-10s %-20s %-10s %-15s %-10s %-10s %-15s %-20s\n", 
            "ID", "Nama Barang", "Jumlah", "Tipe", "Harga Satuan", "Total Harga", "Tanggal", "Keterangan"));

        
        DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            String idTransaksi = model.getValueAt(i, 0).toString();
            String namaBarang = model.getValueAt(i, 1).toString();
            String jumlah = model.getValueAt(i, 2).toString();
            String tipeTransaksi = model.getValueAt(i, 3).toString();
            String hargaSatuan = model.getValueAt(i, 4).toString();
            String totalHarga = model.getValueAt(i, 5).toString();
            String tanggalTransaksi = model.getValueAt(i, 6).toString();
            String keterangan = model.getValueAt(i, 7).toString();

            
            writer.write(String.format("%-10s %-20s %-10s %-15s %-10s %-10s %-15s %-20s\n", 
                idTransaksi, namaBarang, jumlah, tipeTransaksi, hargaSatuan, totalHarga, tanggalTransaksi, keterangan));
        }

        
        writer.close();
        JOptionPane.showMessageDialog(null, "Laporan berhasil dicetak ke laporan_transaksi.txt");

    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencetak laporan: " + e.getMessage());
    }
}



private void resetForm() {
    txtNamaBarang.setText("");
    txtJumlah.setText("");
    cbbTipeTransaksi.setSelectedIndex(0);
    txtHargaSatuan.setText("");
    txtHargaTotal.setText("");
    txtAreaKeterangan.setText("");
}

private void hitungTotalHarga() {
    try {
        
        String jumlahText = txtJumlah.getText();
        String hargaSatuanText = txtHargaSatuan.getText();

        
        if (!jumlahText.isEmpty() && !hargaSatuanText.isEmpty()) {
            int jumlah = Integer.parseInt(jumlahText);
            double hargaSatuan = Double.parseDouble(hargaSatuanText);
            double hargaTotal = jumlah * hargaSatuan;

            
            txtHargaTotal.setText(String.valueOf(hargaTotal));
        } else {
            
            txtHargaTotal.setText("");
        }
    } catch (NumberFormatException e) {
        
        txtHargaTotal.setText("");
    }
}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapusData;
    private javax.swing.JButton btnKembaliMenuUtama;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUlangInput;
    private javax.swing.JComboBox<String> cbbTipeTransaksi;
    private com.toedter.calendar.JDateChooser dateTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextArea txtAreaKeterangan;
    private javax.swing.JTextField txtHargaSatuan;
    private javax.swing.JTextField txtHargaTotal;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables
}
